JNG-3176 Add workflows and update xml files.
BlackBeltTechnology/karaf-features-eclipse-xtext pull request #4
Opened 2022-01-24 09:27 UTC by FarkasValentin

2022-01-28 15:49 UTC, noherczeg approved these changes

2022-03-16 11:35 UTC, noherczeg approved these changes

2022-03-17 19:06 UTC, robertcsakany requested changes

2022-03-17 19:06 UTC, robertcsakany commented on features/pom.xml
> +                            <enableGeneration>true</enableGeneration>
Wrong features are verified. These features belongs to apache-commons. The xtext features have to be validated are defines in features.xml.

2022-03-21 12:07 UTC, blackbelt-oss approved these changes

2022-03-21 12:45 UTC, robertcsakany approved these changes

2022-03-22 15:23 UTC, merged